apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-2-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: hw-2-app
  template:
    metadata:
      labels:
        component: hw-2-app
    spec:
      containers:
        - name: hw-2
          image: "igorizhov/otus_ms_23_hw_1c"
          ports:
            - name: web-hw-2
            - containerPort: 8000
