apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-2-ingress
spec:
  rules:
    - host: arch.homework/health
      http:
        paths:
          - path: /health($|/)(.*)
            backend:
              serviceName: hw-2-service
              servicePort: 8000