apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /health
            backend:
              service:
                 name: hw-2
                 port:
                   number: 8000